name: dart_lint_rules
description: Custom Dart lint rules to be used in Dart libraries.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  lints: ^2.0.1

dev_dependencies:
  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.2.0

  # Testing
  test: ^1.22.0
