name: example_packages
description: Example project of the dart_lint_rules package
version: 0.0.1

environment:
  sdk: '>=2.19.0-444.4.beta <3.0.0'

dev_dependencies:
  dart_lint_rules:
    path: ../

