on:
  # cronjob trigger (every day at 00.00 UTC)
  schedule:
  - cron:  "0 0 * * *"
  # manual trigger
  workflow_dispatch:
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: actions-template-sync
        uses: fabriziocacicia/actions-template-sync@v0.7.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          source_repo_path: ${{ secrets.REPO_OWNER_USERNAME }}/${{ secrets.TEMPLATE_REPO_NAME }}
          pr_labels: 'type: chore'
